export const countryCodes = [
    ['ad', 'Andorra'],
    ['ar', 'Argentina'],
    ['as', 'American Samoa'],
    ['at', 'Austria'],
    ['au', 'Australia'],
    ['bd', 'Bangladesh'],
    ['be', 'Belgium'],
    ['bg', 'Bulgaria'],
    ['br', 'Brazil'],
    ['ca', 'Canada'],
    ['ch', 'Switzerland'],
    ['cz', 'Czech Republic'],
    ['de', 'Germany'],
    ['dk', 'Denmark'],
    ['do', 'Dominican Republic'],
    ['es', 'Spain'],
    ['fi', 'Finland'],
    ['fo', 'Faroe Islands'],
    ['fr', 'France'],
    ['gb', 'Great Britain'],
    ['gf', 'French Guyana'],
    ['gg', 'Guernsey'],
    ['gl', 'Greenland'],
    ['gp', 'Guadeloupe'],
    ['gt', 'Guatemala'],
    ['gu', 'Guam'],
    ['gy', 'Guyana'],
    ['hr', 'Croatia'],
    ['hu', 'Hungary'],
    ['im', 'Isle of Man'],
    ['in', 'India'],
    ['is', 'Iceland'],
    ['it', 'Italy'],
    ['je', 'Jersey'],
    ['jp', 'Japan'],
    ['li', 'Liechtenstein'],
    ['lk', 'Sri Lanka'],
    ['lt', 'Lithuania'],
    ['lu', 'Luxembourg'],
    ['mc', 'Monaco'],
    ['md', 'Moldavia'],
    ['mh', 'Marshall Islands'],
    ['mk', 'Macedonia'],
    ['mp', 'Northern Mariana Islands'],
    ['mq', 'Martinique'],
    ['mx', 'Mexico'],
    ['my', 'Malaysia'],
    ['nl', 'Holland'],
    ['no', 'Norway'],
    ['nz', 'New Zealand'],
    ['ph', 'Phillippines'],
    ['pk', 'Pakistan'],
    ['pl', 'Poland'],
    ['pm', 'Saint Pierre and Miquelon'],
    ['pr', 'Puerto Rico'],
    ['pt', 'Portugal'],
    ['re', 'French Reunion'],
    ['ru', 'Russia'],
    ['se', 'Sweden'],
    ['si', 'Slovenia'],
    ['sj', 'Svalbard & Jan Mayen Islands'],
    ['sk', 'Slovak Republic'],
    ['sm', 'San Marino'],
    ['th', 'Thailand'],
    ['tr', 'Turkey'],
    ['us', 'United States'],
    ['va', 'Vatican'],
    ['vi', 'Virgin Islands'],
    ['yt', 'Mayotte'],
    ['za', 'South Africa']
]